### ISSUE TITLE
How to build this with Visual Studio 2017 Community Edition?

### ISSUE THREAD

**Issue by smuehlst** [flypie/GDummyPanel#1]
I'm trying to build this Visual Studio 2017 Community Edition. It fails to build because of a missing include file "curses.h". The project references the additional include directory C:\cygwin64\home\John-Bradley\PDCursesNonOffical.

What are the additional dependencies for building this application?

**Comment by flypie** [comment]
You need to get hold of PDCurses.   This is the version I built and use https://www.projectpluto.com/win32a.htm 
I got it from git and built using   "nmake -f vcwin32.mak WIDE=Y DLL=Y" in the WIN32a subdir.

GDummyPanel should be considered Alpha level. Only I have run it as far as I know. Check for updates regularly.

Don't run it inside VC IDE run it from either command line or desktop other wise the output get redirected to the IDE window and it all goes wrong.

**Comment by smuehlst** [comment]
Thanks, I will give the build with PDCurses a try. Maybe it would be possible to check out PDCurses as a Git submodule of your GDummyProject, so it could be built automatically with it.
